version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@angular/cli"
    versions:
    - "> 10.2.0"
  - dependency-name: aws-amplify
    versions:
    - "> 3.0.22"
  - dependency-name: "@aws-amplify/pubsub"
    versions:
    - "> 3.0.25"
  - dependency-name: caniuse-lite
    versions:
    - "> 1.0.30001133, < 1.1"
  - dependency-name: cypress
    versions:
    - 6.3.0
    - 6.4.0
    - 6.5.0
    - 6.6.0
    - 7.1.0
  - dependency-name: rollup
    versions:
    - 2.38.0
    - 2.38.3
    - 2.38.5
    - 2.39.0
    - 2.40.0
    - 2.41.0
    - 2.41.2
    - 2.42.2
    - 2.43.1
    - 2.44.0
  - dependency-name: "@angular/language-service"
    versions:
    - 11.1.0
    - 11.1.1
    - 11.1.2
    - 11.2.0
    - 11.2.1
    - 11.2.3
    - 11.2.4
    - 11.2.5
    - 11.2.6
    - 11.2.7
    - 11.2.8
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: karma
    versions:
    - 6.0.1
    - 6.0.3
    - 6.1.0
    - 6.1.1
    - 6.1.2
    - 6.2.0
    - 6.3.1
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.25
    - 14.14.28
    - 14.14.31
    - 14.14.32
    - 14.14.34
    - 14.14.35
  - dependency-name: husky
    versions:
    - 4.3.8
    - 5.0.9
    - 5.1.0
    - 5.1.2
    - 5.1.3
    - 5.2.0
  - dependency-name: "@sentry/browser"
    versions:
    - 6.0.1
    - 6.0.3
    - 6.1.0
    - 6.2.0
    - 6.2.1
  - dependency-name: browserslist
    versions:
    - 4.16.1
  - dependency-name: "@react-native-community/netinfo"
    versions:
    - 5.9.10
