version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    reviewers:
      - Health-Education-England/internal-admin-frontend

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    reviewers:
      - Health-Education-England/internal-admin-frontend
      - Health-Education-England/internal-admin-devops
