export const underNoticeResponse1 = {
  countTotal: 22070,
  countUnderNotice: 5018,
  totalPages: 251,
  traineeInfo: [
    {
      gmcReferenceNumber: "7139992",
      doctorFirstName: "Olufunto Temitope",
      doctorLastName: "Segun",
      submissionDate: "2015-09-08",
      dateAdded: "2019-12-30",
      underNotice: "ON_HOLD",
      sanction: "No",
      doctorStatus: "",
      programmeName: "",
      programmeMembershipType: "",
      cctDate: "2020-04-10",
      admin: "",
      lastUpdatedDate: "2020-04-10"
    },
    {
      gmcReferenceNumber: "6059995",
      doctorFirstName: "Madhavan Chikkapapanna",
      doctorLastName: "Papanna",
      submissionDate: "2015-09-08",
      dateAdded: "2019-10-21",
      underNotice: "ON_HOLD",
      sanction: "No",
      doctorStatus: "",
      programmeName: "",
      programmeMembershipType: "",
      cctDate: "2020-04-10",
      admin: "",
      lastUpdatedDate: "2020-04-10"
    },
    {
      gmcReferenceNumber: "7079990",
      doctorFirstName: "Alistair Gordon",
      doctorLastName: "White",
      submissionDate: "2015-09-08",
      dateAdded: "2018-05-09",
      underNotice: "ON_HOLD",
      sanction: "No",
      doctorStatus: "",
      programmeName: "",
      programmeMembershipType: "",
      cctDate: "2020-04-10",
      admin: "",
      lastUpdatedDate: "2020-04-10"
    },
    {
      gmcReferenceNumber: "7079991",
      doctorFirstName: "Alexander Michael",
      doctorLastName: "Whittam",
      submissionDate: "2015-09-08",
      dateAdded: "2018-05-09",
      underNotice: "ON_HOLD",
      sanction: "No",
      doctorStatus: "",
      programmeName: "",
      programmeMembershipType: "",
      cctDate: "2020-04-10",
      admin: "",
      lastUpdatedDate: "2020-04-10"
    },
    {
      gmcReferenceNumber: "7079996",
      doctorFirstName: "Wendy",
      doctorLastName: "Wong",
      submissionDate: "2015-09-08",
      dateAdded: "2018-05-09",
      underNotice: "ON_HOLD",
      sanction: "No",
      doctorStatus: "",
      programmeName: "",
      programmeMembershipType: "",
      cctDate: "2020-04-10",
      admin: "",
      lastUpdatedDate: "2020-04-10"
    },
    {
      gmcReferenceNumber: "7439992",
      doctorFirstName: "Margaret Ma",
      doctorLastName: "Huang",
      submissionDate: "2015-09-08",
      dateAdded: "2018-03-20",
      underNotice: "ON_HOLD",
      sanction: "No",
      doctorStatus: "",
      programmeName: "",
      programmeMembershipType: "",
      cctDate: "2020-04-10",
      admin: "",
      lastUpdatedDate: "2020-04-10"
    },
    {
      gmcReferenceNumber: "7139723",
      doctorFirstName: "Katy Fiona",
      doctorLastName: "Hosie",
      submissionDate: "2015-09-06",
      dateAdded: "2019-12-28",
      underNotice: "YES",
      sanction: "No",
      doctorStatus: "",
      programmeName: "",
      programmeMembershipType: "",
      cctDate: "2020-04-10",
      admin: "",
      lastUpdatedDate: "2020-04-10"
    },
    {
      gmcReferenceNumber: "7139786",
      doctorFirstName: "Lorna Jane",
      doctorLastName: "Willoughby",
      submissionDate: "2015-09-06",
      dateAdded: "2019-12-28",
      underNotice: "YES",
      sanction: "No",
      doctorStatus: "",
      programmeName: "",
      programmeMembershipType: "",
      cctDate: "2020-04-10",
      admin: "",
      lastUpdatedDate: "2020-04-10"
    },
    {
      gmcReferenceNumber: "7419724",
      doctorFirstName: "Mary",
      doctorLastName: "Zadik",
      submissionDate: "2015-09-06",
      dateAdded: "2019-08-30",
      underNotice: "YES",
      sanction: "No",
      doctorStatus: "",
      programmeName: "",
      programmeMembershipType: "",
      cctDate: "2020-04-10",
      admin: "",
      lastUpdatedDate: "2020-04-10"
    },
    {
      gmcReferenceNumber: "7419750",
      doctorFirstName: "Steffan Rhys",
      doctorLastName: "Owen",
      submissionDate: "2015-09-06",
      dateAdded: "2019-08-30",
      underNotice: "YES",
      sanction: "No",
      doctorStatus: "",
      programmeName: "",
      programmeMembershipType: "",
      cctDate: "2020-04-10",
      admin: "",
      lastUpdatedDate: "2020-04-10"
    },
    {
      gmcReferenceNumber: "7019778",
      doctorFirstName: "Hosam El-Din",
      doctorLastName: "Matar",
      submissionDate: "2015-09-06",
      dateAdded: "2018-09-14",
      underNotice: "YES",
      sanction: "No",
      doctorStatus: "",
      programmeName: "",
      programmeMembershipType: "",
      cctDate: "2020-04-10",
      admin: "",
      lastUpdatedDate: "2020-04-10"
    },
    {
      gmcReferenceNumber: "7039755",
      doctorFirstName: "Benjamin Michael",
      doctorLastName: "Kolb",
      submissionDate: "2015-09-06",
      dateAdded: "2019-04-02",
      underNotice: "YES",
      sanction: "No",
      doctorStatus: "",
      programmeName: "",
      programmeMembershipType: "",
      cctDate: "2020-04-10",
      admin: "",
      lastUpdatedDate: "2020-04-10"
    },
    {
      gmcReferenceNumber: "7039762",
      doctorFirstName: "Thomas",
      doctorLastName: "Lamb",
      submissionDate: "2015-09-06",
      dateAdded: "2019-04-02",
      underNotice: "YES",
      sanction: "No",
      doctorStatus: "",
      programmeName: "",
      programmeMembershipType: "",
      cctDate: "2020-04-10",
      admin: "",
      lastUpdatedDate: "2020-04-10"
    },
    {
      gmcReferenceNumber: "7139701",
      doctorFirstName: "Ravi",
      doctorLastName: "Gupta",
      submissionDate: "2015-09-06",
      dateAdded: "2019-12-28",
      underNotice: "YES",
      sanction: "No",
      doctorStatus: "",
      programmeName: "",
      programmeMembershipType: "",
      cctDate: "2020-04-10",
      admin: "",
      lastUpdatedDate: "2020-04-10"
    },
    {
      gmcReferenceNumber: "7139784",
      doctorFirstName: "Sarah Catherine",
      doctorLastName: "White",
      submissionDate: "2015-09-06",
      dateAdded: "2019-12-28",
      underNotice: "YES",
      sanction: "No",
      doctorStatus: "",
      programmeName: "",
      programmeMembershipType: "",
      cctDate: "2020-04-10",
      admin: "",
      lastUpdatedDate: "2020-04-10"
    },
    {
      gmcReferenceNumber: "7419701",
      doctorFirstName: "Andrew John",
      doctorLastName: "Starkie",
      submissionDate: "2015-09-06",
      dateAdded: "2019-08-30",
      underNotice: "YES",
      sanction: "No",
      doctorStatus: "",
      programmeName: "",
      programmeMembershipType: "",
      cctDate: "2020-04-10",
      admin: "",
      lastUpdatedDate: "2020-04-10"
    },
    {
      gmcReferenceNumber: "7419713",
      doctorFirstName: "Jon Jurriaan",
      doctorLastName: "Van Aartsen",
      submissionDate: "2015-09-06",
      dateAdded: "2019-08-30",
      underNotice: "YES",
      sanction: "No",
      doctorStatus: "",
      programmeName: "",
      programmeMembershipType: "",
      cctDate: "2020-04-10",
      admin: "",
      lastUpdatedDate: "2020-04-10"
    },
    {
      gmcReferenceNumber: "7419726",
      doctorFirstName: "Fatemeh",
      doctorLastName: "Ziaei",
      submissionDate: "2015-09-06",
      dateAdded: "2019-08-30",
      underNotice: "YES",
      sanction: "No",
      doctorStatus: "",
      programmeName: "",
      programmeMembershipType: "",
      cctDate: "2020-04-10",
      admin: "",
      lastUpdatedDate: "2020-04-10"
    },
    {
      gmcReferenceNumber: "7419732",
      doctorFirstName: "Caradoc",
      doctorLastName: "Morris",
      submissionDate: "2015-09-06",
      dateAdded: "2019-08-30",
      underNotice: "YES",
      sanction: "No",
      doctorStatus: "",
      programmeName: "",
      programmeMembershipType: "",
      cctDate: "2020-04-10",
      admin: "",
      lastUpdatedDate: "2020-04-10"
    },
    {
      gmcReferenceNumber: "7419751",
      doctorFirstName: "Toluwani Titilopemi",
      doctorLastName: "Oyewale",
      submissionDate: "2015-09-06",
      dateAdded: "2019-08-30",
      underNotice: "YES",
      sanction: "No",
      doctorStatus: "",
      programmeName: "",
      programmeMembershipType: "",
      cctDate: "2020-04-10",
      admin: "",
      lastUpdatedDate: "2020-04-10"
    }
  ]
};
export const underNoticeResponse2 = {
  countTotal: 22070,
  countUnderNotice: 5018,
  totalPages: 251,
  traineeInfo: [
    {
      gmcReferenceNumber: "6159744",
      doctorFirstName: "Dhaara",
      doctorLastName: "Iyer",
      submissionDate: "2015-09-06",
      dateAdded: "2018-07-16",
      underNotice: "YES",
      sanction: "No",
      doctorStatus: "",
      programmeName: "",
      programmeMembershipType: "",
      cctDate: "2020-04-10",
      admin: "",
      lastUpdatedDate: "2020-04-10"
    },
    {
      gmcReferenceNumber: "6159794",
      doctorFirstName: "Rulla Adnan Hameed",
      doctorLastName: "Al-Araji",
      submissionDate: "2015-09-06",
      dateAdded: "2018-07-16",
      underNotice: "YES",
      sanction: "No",
      doctorStatus: "",
      programmeName: "",
      programmeMembershipType: "",
      cctDate: "2020-04-10",
      admin: "",
      lastUpdatedDate: "2020-04-10"
    },
    {
      gmcReferenceNumber: "7039745",
      doctorFirstName: "David",
      doctorLastName: "Janowicz",
      submissionDate: "2015-09-06",
      dateAdded: "2019-04-02",
      underNotice: "YES",
      sanction: "No",
      doctorStatus: "",
      programmeName: "",
      programmeMembershipType: "",
      cctDate: "2020-04-10",
      admin: "",
      lastUpdatedDate: "2020-04-10"
    },
    {
      gmcReferenceNumber: "7059731",
      doctorFirstName: "Pushkin",
      doctorLastName: "Reza",
      submissionDate: "2015-09-06",
      dateAdded: "2019-10-19",
      underNotice: "YES",
      sanction: "No",
      doctorStatus: "",
      programmeName: "",
      programmeMembershipType: "",
      cctDate: "2020-04-10",
      admin: "",
      lastUpdatedDate: "2020-04-10"
    },
    {
      gmcReferenceNumber: "7059796",
      doctorFirstName: "Sasan",
      doctorLastName: "Iraji",
      submissionDate: "2015-09-06",
      dateAdded: "2019-10-19",
      underNotice: "YES",
      sanction: "No",
      doctorStatus: "",
      programmeName: "",
      programmeMembershipType: "",
      cctDate: "2020-04-10",
      admin: "",
      lastUpdatedDate: "2020-04-10"
    },
    {
      gmcReferenceNumber: "7079798",
      doctorFirstName: "Samantha",
      doctorLastName: "Prior",
      submissionDate: "2015-09-06",
      dateAdded: "2018-05-07",
      underNotice: "YES",
      sanction: "No",
      doctorStatus: "",
      programmeName: "",
      programmeMembershipType: "",
      cctDate: "2020-04-10",
      admin: "",
      lastUpdatedDate: "2020-04-10"
    },
    {
      gmcReferenceNumber: "7139779",
      doctorFirstName: "Kathryn",
      doctorLastName: "Waite",
      submissionDate: "2015-09-06",
      dateAdded: "2019-12-28",
      underNotice: "YES",
      sanction: "No",
      doctorStatus: "",
      programmeName: "",
      programmeMembershipType: "",
      cctDate: "2020-04-10",
      admin: "",
      lastUpdatedDate: "2020-04-10"
    },
    {
      gmcReferenceNumber: "7299775",
      doctorFirstName: "Adebisi Adetoke",
      doctorLastName: "Ogundipe",
      submissionDate: "2015-09-06",
      dateAdded: "2018-05-17",
      underNotice: "YES",
      sanction: "No",
      doctorStatus: "",
      programmeName: "",
      programmeMembershipType: "",
      cctDate: "2020-04-10",
      admin: "",
      lastUpdatedDate: "2020-04-10"
    },
    {
      gmcReferenceNumber: "7419747",
      doctorFirstName: "Olaomopo",
      doctorLastName: "Omisade",
      submissionDate: "2015-09-06",
      dateAdded: "2019-08-30",
      underNotice: "YES",
      sanction: "No",
      doctorStatus: "",
      programmeName: "",
      programmeMembershipType: "",
      cctDate: "2020-04-10",
      admin: "",
      lastUpdatedDate: "2020-04-10"
    },
    {
      gmcReferenceNumber: "7039710",
      doctorFirstName: "Charlotte Ruth",
      doctorLastName: "Anderson",
      submissionDate: "2015-09-06",
      dateAdded: "2019-04-02",
      underNotice: "YES",
      sanction: "No",
      doctorStatus: "",
      programmeName: "",
      programmeMembershipType: "",
      cctDate: "2020-04-10",
      admin: "",
      lastUpdatedDate: "2020-04-10"
    },
    {
      gmcReferenceNumber: "7039715",
      doctorFirstName: "Alice Laura",
      doctorLastName: "Baldwin",
      submissionDate: "2015-09-06",
      dateAdded: "2019-04-02",
      underNotice: "YES",
      sanction: "No",
      doctorStatus: "",
      programmeName: "",
      programmeMembershipType: "",
      cctDate: "2020-04-10",
      admin: "",
      lastUpdatedDate: "2020-04-10"
    },
    {
      gmcReferenceNumber: "7039716",
      doctorFirstName: "Katherine Elizabeth",
      doctorLastName: "Banyard",
      submissionDate: "2015-09-06",
      dateAdded: "2019-04-02",
      underNotice: "YES",
      sanction: "No",
      doctorStatus: "",
      programmeName: "",
      programmeMembershipType: "",
      cctDate: "2020-04-10",
      admin: "",
      lastUpdatedDate: "2020-04-10"
    },
    {
      gmcReferenceNumber: "7039748",
      doctorFirstName: "Naomi Kate",
      doctorLastName: "Johnson",
      submissionDate: "2015-09-06",
      dateAdded: "2019-04-02",
      underNotice: "YES",
      sanction: "No",
      doctorStatus: "",
      programmeName: "",
      programmeMembershipType: "",
      cctDate: "2020-04-10",
      admin: "",
      lastUpdatedDate: "2020-04-10"
    },
    {
      gmcReferenceNumber: "7039760",
      doctorFirstName: "Christopher Lewis",
      doctorLastName: "Lamare",
      submissionDate: "2015-09-06",
      dateAdded: "2019-04-02",
      underNotice: "YES",
      sanction: "No",
      doctorStatus: "",
      programmeName: "",
      programmeMembershipType: "",
      cctDate: "2020-04-10",
      admin: "",
      lastUpdatedDate: "2020-04-10"
    },
    {
      gmcReferenceNumber: "7039766",
      doctorFirstName: "Hannah Elizabeth",
      doctorLastName: "Lauder",
      submissionDate: "2015-09-06",
      dateAdded: "2019-04-02",
      underNotice: "YES",
      sanction: "No",
      doctorStatus: "",
      programmeName: "",
      programmeMembershipType: "",
      cctDate: "2020-04-10",
      admin: "",
      lastUpdatedDate: "2020-04-10"
    },
    {
      gmcReferenceNumber: "7039767",
      doctorFirstName: "Nicholas Charles William",
      doctorLastName: "Laundy",
      submissionDate: "2015-09-06",
      dateAdded: "2019-04-02",
      underNotice: "YES",
      sanction: "No",
      doctorStatus: "",
      programmeName: "",
      programmeMembershipType: "",
      cctDate: "2020-04-10",
      admin: "",
      lastUpdatedDate: "2020-04-10"
    },
    {
      gmcReferenceNumber: "7039774",
      doctorFirstName: "Thomas Anthony Richard",
      doctorLastName: "Mace",
      submissionDate: "2015-09-06",
      dateAdded: "2019-04-02",
      underNotice: "YES",
      sanction: "No",
      doctorStatus: "",
      programmeName: "",
      programmeMembershipType: "",
      cctDate: "2020-04-10",
      admin: "",
      lastUpdatedDate: "2020-04-10"
    },
    {
      gmcReferenceNumber: "7039784",
      doctorFirstName: "James Alexander",
      doctorLastName: "Briscoe",
      submissionDate: "2015-09-06",
      dateAdded: "2019-04-02",
      underNotice: "YES",
      sanction: "No",
      doctorStatus: "",
      programmeName: "",
      programmeMembershipType: "",
      cctDate: "2020-04-10",
      admin: "",
      lastUpdatedDate: "2020-04-10"
    },
    {
      gmcReferenceNumber: "7039795",
      doctorFirstName: "Rory Jefferson",
      doctorLastName: "Colhoun",
      submissionDate: "2015-09-06",
      dateAdded: "2019-04-02",
      underNotice: "YES",
      sanction: "No",
      doctorStatus: "",
      programmeName: "",
      programmeMembershipType: "",
      cctDate: "2020-04-10",
      admin: "",
      lastUpdatedDate: "2020-04-10"
    },
    {
      gmcReferenceNumber: "7139709",
      doctorFirstName: "Yousuf",
      doctorLastName: "Hanif",
      submissionDate: "2015-09-06",
      dateAdded: "2019-12-28",
      underNotice: "YES",
      sanction: "No",
      doctorStatus: "",
      programmeName: "",
      programmeMembershipType: "",
      cctDate: "2020-04-10",
      admin: "",
      lastUpdatedDate: "2020-04-10"
    }
  ]
};
export const traineesResponse1 = {
  countTotal: 22070,
  countUnderNotice: 5018,
  totalPages: 1104,
  traineeInfo: [
    {
      gmcReferenceNumber: "5199953",
      doctorFirstName: "Jagadish Venkat",
      doctorLastName: "Malla",
      submissionDate: "2015-09-08",
      dateAdded: "2019-08-22",
      underNotice: "NO",
      sanction: "No",
      doctorStatus: "",
      programmeName: "",
      programmeMembershipType: "",
      cctDate: "2020-04-10",
      admin: "",
      lastUpdatedDate: "2020-04-10"
    },
    {
      gmcReferenceNumber: "6119989",
      doctorFirstName: "Uma",
      doctorLastName: "Varma",
      submissionDate: "2015-09-08",
      dateAdded: "2019-06-13",
      underNotice: "NO",
      sanction: "No",
      doctorStatus: "",
      programmeName: "",
      programmeMembershipType: "",
      cctDate: "2020-04-10",
      admin: "",
      lastUpdatedDate: "2020-04-10"
    },
    {
      gmcReferenceNumber: "6159948",
      doctorFirstName: "Abubaker Yousif Mohamed",
      doctorLastName: "Ahmed",
      submissionDate: "2015-09-08",
      dateAdded: "2018-07-18",
      underNotice: "NO",
      sanction: "No",
      doctorStatus: "",
      programmeName: "",
      programmeMembershipType: "",
      cctDate: "2020-04-10",
      admin: "",
      lastUpdatedDate: "2020-04-10"
    },
    {
      gmcReferenceNumber: "7019924",
      doctorFirstName: "Chinonye Eleanor",
      doctorLastName: "Otu",
      submissionDate: "2015-09-08",
      dateAdded: "2018-09-16",
      underNotice: "NO",
      sanction: "No",
      doctorStatus: "",
      programmeName: "",
      programmeMembershipType: "",
      cctDate: "2020-04-10",
      admin: "",
      lastUpdatedDate: "2020-04-10"
    },
    {
      gmcReferenceNumber: "7039907",
      doctorFirstName: "Anneliese Natasha Maya",
      doctorLastName: "Simons",
      submissionDate: "2015-09-08",
      dateAdded: "2019-04-04",
      underNotice: "NO",
      sanction: "No",
      doctorStatus: "",
      programmeName: "",
      programmeMembershipType: "",
      cctDate: "2020-04-10",
      admin: "",
      lastUpdatedDate: "2020-04-10"
    },
    {
      gmcReferenceNumber: "7079920",
      doctorFirstName: "Oliver Matthew",
      doctorLastName: "Ellis",
      submissionDate: "2015-09-08",
      dateAdded: "2018-05-09",
      underNotice: "NO",
      sanction: "No",
      doctorStatus: "",
      programmeName: "",
      programmeMembershipType: "",
      cctDate: "2020-04-10",
      admin: "",
      lastUpdatedDate: "2020-04-10"
    },
    {
      gmcReferenceNumber: "7079970",
      doctorFirstName: "Abbie Loren",
      doctorLastName: "Gregory",
      submissionDate: "2015-09-08",
      dateAdded: "2018-05-09",
      underNotice: "NO",
      sanction: "No",
      doctorStatus: "",
      programmeName: "",
      programmeMembershipType: "",
      cctDate: "2020-04-10",
      admin: "",
      lastUpdatedDate: "2020-04-10"
    },
    {
      gmcReferenceNumber: "7139992",
      doctorFirstName: "Olufunto Temitope",
      doctorLastName: "Segun",
      submissionDate: "2015-09-08",
      dateAdded: "2019-12-30",
      underNotice: "ON_HOLD",
      sanction: "No",
      doctorStatus: "",
      programmeName: "",
      programmeMembershipType: "",
      cctDate: "2020-04-10",
      admin: "",
      lastUpdatedDate: "2020-04-10"
    },
    {
      gmcReferenceNumber: "7259910",
      doctorFirstName: "Aliki",
      doctorLastName: "Bogiatzopoulou",
      submissionDate: "2015-09-08",
      dateAdded: "2019-04-14",
      underNotice: "NO",
      sanction: "No",
      doctorStatus: "",
      programmeName: "",
      programmeMembershipType: "",
      cctDate: "2020-04-10",
      admin: "",
      lastUpdatedDate: "2020-04-10"
    },
    {
      gmcReferenceNumber: "7139943",
      doctorFirstName: "ATENA",
      doctorLastName: "GOGOKHIA",
      submissionDate: "2015-09-08",
      dateAdded: "2019-12-30",
      underNotice: "NO",
      sanction: "No",
      doctorStatus: "",
      programmeName: "",
      programmeMembershipType: "",
      cctDate: "2020-04-10",
      admin: "",
      lastUpdatedDate: "2020-04-10"
    },
    {
      gmcReferenceNumber: "5199989",
      doctorFirstName: "Swaroop Anshuman",
      doctorLastName: "Roy",
      submissionDate: "2015-09-08",
      dateAdded: "2019-08-22",
      underNotice: "NO",
      sanction: "No",
      doctorStatus: "",
      programmeName: "",
      programmeMembershipType: "",
      cctDate: "2020-04-10",
      admin: "",
      lastUpdatedDate: "2020-04-10"
    },
    {
      gmcReferenceNumber: "6059995",
      doctorFirstName: "Madhavan Chikkapapanna",
      doctorLastName: "Papanna",
      submissionDate: "2015-09-08",
      dateAdded: "2019-10-21",
      underNotice: "ON_HOLD",
      sanction: "No",
      doctorStatus: "",
      programmeName: "",
      programmeMembershipType: "",
      cctDate: "2020-04-10",
      admin: "",
      lastUpdatedDate: "2020-04-10"
    },
    {
      gmcReferenceNumber: "6079988",
      doctorFirstName: "Rasheed Adebayo",
      doctorLastName: "Afinowi",
      submissionDate: "2015-09-08",
      dateAdded: "2018-05-09",
      underNotice: "NO",
      sanction: "No",
      doctorStatus: "",
      programmeName: "",
      programmeMembershipType: "",
      cctDate: "2020-04-10",
      admin: "",
      lastUpdatedDate: "2020-04-10"
    },
    {
      gmcReferenceNumber: "6139908",
      doctorFirstName: "Yasmin",
      doctorLastName: "Zaidy",
      submissionDate: "2015-09-08",
      dateAdded: "2019-12-30",
      underNotice: "NO",
      sanction: "No",
      doctorStatus: "",
      programmeName: "",
      programmeMembershipType: "",
      cctDate: "2020-04-10",
      admin: "",
      lastUpdatedDate: "2020-04-10"
    },
    {
      gmcReferenceNumber: "7019929",
      doctorFirstName: "Md Wali-Ur",
      doctorLastName: "Rahman",
      submissionDate: "2015-09-08",
      dateAdded: "2018-09-16",
      underNotice: "NO",
      sanction: "No",
      doctorStatus: "",
      programmeName: "",
      programmeMembershipType: "",
      cctDate: "2020-04-10",
      admin: "",
      lastUpdatedDate: "2020-04-10"
    },
    {
      gmcReferenceNumber: "7039913",
      doctorFirstName: "Richard James",
      doctorLastName: "Stevens",
      submissionDate: "2015-09-08",
      dateAdded: "2019-04-04",
      underNotice: "NO",
      sanction: "No",
      doctorStatus: "",
      programmeName: "",
      programmeMembershipType: "",
      cctDate: "2020-04-10",
      admin: "",
      lastUpdatedDate: "2020-04-10"
    },
    {
      gmcReferenceNumber: "7039930",
      doctorFirstName: "Nicholas David",
      doctorLastName: "Weatherley",
      submissionDate: "2015-09-08",
      dateAdded: "2019-04-04",
      underNotice: "NO",
      sanction: "No",
      doctorStatus: "",
      programmeName: "",
      programmeMembershipType: "",
      cctDate: "2020-04-10",
      admin: "",
      lastUpdatedDate: "2020-04-10"
    },
    {
      gmcReferenceNumber: "7039932",
      doctorFirstName: "James Paul",
      doctorLastName: "White",
      submissionDate: "2015-09-08",
      dateAdded: "2019-04-04",
      underNotice: "NO",
      sanction: "No",
      doctorStatus: "",
      programmeName: "",
      programmeMembershipType: "",
      cctDate: "2020-04-10",
      admin: "",
      lastUpdatedDate: "2020-04-10"
    },
    {
      gmcReferenceNumber: "7079902",
      doctorFirstName: "Laura Michelle",
      doctorLastName: "Cressey",
      submissionDate: "2015-09-08",
      dateAdded: "2018-05-09",
      underNotice: "NO",
      sanction: "No",
      doctorStatus: "",
      programmeName: "",
      programmeMembershipType: "",
      cctDate: "2020-04-10",
      admin: "",
      lastUpdatedDate: "2020-04-10"
    },
    {
      gmcReferenceNumber: "7079918",
      doctorFirstName: "Robert",
      doctorLastName: "Eastham",
      submissionDate: "2015-09-08",
      dateAdded: "2018-05-09",
      underNotice: "NO",
      sanction: "No",
      doctorStatus: "",
      programmeName: "",
      programmeMembershipType: "",
      cctDate: "2020-04-10",
      admin: "",
      lastUpdatedDate: "2020-04-10"
    }
  ]
};
export const traineesResponse2 = {
  countTotal: 22070,
  countUnderNotice: 5018,
  totalPages: 1104,
  traineeInfo: [
    {
      gmcReferenceNumber: "7079934",
      doctorFirstName: "Rose Elizabeth Corinna",
      doctorLastName: "Mozdiak",
      submissionDate: "2015-09-08",
      dateAdded: "2018-05-09",
      underNotice: "NO",
      sanction: "No",
      doctorStatus: "",
      programmeName: "",
      programmeMembershipType: "",
      cctDate: "2020-04-10",
      admin: "",
      lastUpdatedDate: "2020-04-10"
    },
    {
      gmcReferenceNumber: "7079948",
      doctorFirstName: "Heather Louise",
      doctorLastName: "Parr",
      submissionDate: "2015-09-08",
      dateAdded: "2018-05-09",
      underNotice: "NO",
      sanction: "No",
      doctorStatus: "",
      programmeName: "",
      programmeMembershipType: "",
      cctDate: "2020-04-10",
      admin: "",
      lastUpdatedDate: "2020-04-10"
    },
    {
      gmcReferenceNumber: "7079955",
      doctorFirstName: "Matthew James",
      doctorLastName: "Pinder",
      submissionDate: "2015-09-08",
      dateAdded: "2018-05-09",
      underNotice: "NO",
      sanction: "No",
      doctorStatus: "",
      programmeName: "",
      programmeMembershipType: "",
      cctDate: "2020-04-10",
      admin: "",
      lastUpdatedDate: "2020-04-10"
    },
    {
      gmcReferenceNumber: "7079957",
      doctorFirstName: "Claire",
      doctorLastName: "Winton",
      submissionDate: "2015-09-08",
      dateAdded: "2018-05-09",
      underNotice: "NO",
      sanction: "No",
      doctorStatus: "",
      programmeName: "",
      programmeMembershipType: "",
      cctDate: "2020-04-10",
      admin: "",
      lastUpdatedDate: "2020-04-10"
    },
    {
      gmcReferenceNumber: "7079989",
      doctorFirstName: "Peter John",
      doctorLastName: "Webster",
      submissionDate: "2015-09-08",
      dateAdded: "2018-05-09",
      underNotice: "NO",
      sanction: "No",
      doctorStatus: "",
      programmeName: "",
      programmeMembershipType: "",
      cctDate: "2020-04-10",
      admin: "",
      lastUpdatedDate: "2020-04-10"
    },
    {
      gmcReferenceNumber: "7079990",
      doctorFirstName: "Alistair Gordon",
      doctorLastName: "White",
      submissionDate: "2015-09-08",
      dateAdded: "2018-05-09",
      underNotice: "ON_HOLD",
      sanction: "No",
      doctorStatus: "",
      programmeName: "",
      programmeMembershipType: "",
      cctDate: "2020-04-10",
      admin: "",
      lastUpdatedDate: "2020-04-10"
    },
    {
      gmcReferenceNumber: "7079991",
      doctorFirstName: "Alexander Michael",
      doctorLastName: "Whittam",
      submissionDate: "2015-09-08",
      dateAdded: "2018-05-09",
      underNotice: "ON_HOLD",
      sanction: "No",
      doctorStatus: "",
      programmeName: "",
      programmeMembershipType: "",
      cctDate: "2020-04-10",
      admin: "",
      lastUpdatedDate: "2020-04-10"
    },
    {
      gmcReferenceNumber: "7079996",
      doctorFirstName: "Wendy",
      doctorLastName: "Wong",
      submissionDate: "2015-09-08",
      dateAdded: "2018-05-09",
      underNotice: "ON_HOLD",
      sanction: "No",
      doctorStatus: "",
      programmeName: "",
      programmeMembershipType: "",
      cctDate: "2020-04-10",
      admin: "",
      lastUpdatedDate: "2020-04-10"
    },
    {
      gmcReferenceNumber: "7179933",
      doctorFirstName: "Samuel",
      doctorLastName: "Osieku",
      submissionDate: "2015-09-08",
      dateAdded: "2019-02-03",
      underNotice: "NO",
      sanction: "No",
      doctorStatus: "",
      programmeName: "",
      programmeMembershipType: "",
      cctDate: "2020-04-10",
      admin: "",
      lastUpdatedDate: "2020-04-10"
    },
    {
      gmcReferenceNumber: "6079939",
      doctorFirstName: "Behrooz",
      doctorLastName: "Haddad",
      submissionDate: "2015-09-08",
      dateAdded: "2018-05-09",
      underNotice: "NO",
      sanction: "No",
      doctorStatus: "",
      programmeName: "",
      programmeMembershipType: "",
      cctDate: "2020-04-10",
      admin: "",
      lastUpdatedDate: "2020-04-10"
    },
    {
      gmcReferenceNumber: "6139989",
      doctorFirstName: "Yasir",
      doctorLastName: "Hameed",
      submissionDate: "2015-09-08",
      dateAdded: "2019-12-30",
      underNotice: "NO",
      sanction: "No",
      doctorStatus: "",
      programmeName: "",
      programmeMembershipType: "",
      cctDate: "2020-04-10",
      admin: "",
      lastUpdatedDate: "2020-04-10"
    },
    {
      gmcReferenceNumber: "7059921",
      doctorFirstName: "Khushboo Anwer",
      doctorLastName: "Magsi",
      submissionDate: "2015-09-08",
      dateAdded: "2019-10-21",
      underNotice: "NO",
      sanction: "No",
      doctorStatus: "",
      programmeName: "",
      programmeMembershipType: "",
      cctDate: "2020-04-10",
      admin: "",
      lastUpdatedDate: "2020-04-10"
    },
    {
      gmcReferenceNumber: "7079912",
      doctorFirstName: "Amy",
      doctorLastName: "Teare",
      submissionDate: "2015-09-08",
      dateAdded: "2018-05-09",
      underNotice: "NO",
      sanction: "No",
      doctorStatus: "",
      programmeName: "",
      programmeMembershipType: "",
      cctDate: "2020-04-10",
      admin: "",
      lastUpdatedDate: "2020-04-10"
    },
    {
      gmcReferenceNumber: "7079976",
      doctorFirstName: "Makabongwe",
      doctorLastName: "Tshuma",
      submissionDate: "2015-09-08",
      dateAdded: "2018-05-09",
      underNotice: "NO",
      sanction: "No",
      doctorStatus: "",
      programmeName: "",
      programmeMembershipType: "",
      cctDate: "2020-04-10",
      admin: "",
      lastUpdatedDate: "2020-04-10"
    },
    {
      gmcReferenceNumber: "7199945",
      doctorFirstName: "Carlo",
      doctorLastName: "Gravina",
      submissionDate: "2015-09-08",
      dateAdded: "2019-08-22",
      underNotice: "NO",
      sanction: "No",
      doctorStatus: "",
      programmeName: "",
      programmeMembershipType: "",
      cctDate: "2020-04-10",
      admin: "",
      lastUpdatedDate: "2020-04-10"
    },
    {
      gmcReferenceNumber: "7439915",
      doctorFirstName: "Johan Safree",
      doctorLastName: "Aris Chandran",
      submissionDate: "2015-09-08",
      dateAdded: "2018-03-20",
      underNotice: "NO",
      sanction: "No",
      doctorStatus: "",
      programmeName: "",
      programmeMembershipType: "",
      cctDate: "2020-04-10",
      admin: "",
      lastUpdatedDate: "2020-04-10"
    },
    {
      gmcReferenceNumber: "7439959",
      doctorFirstName: "Harshita Kanaiyalal",
      doctorLastName: "Goradia",
      submissionDate: "2015-09-08",
      dateAdded: "2018-03-20",
      underNotice: "NO",
      sanction: "No",
      doctorStatus: "",
      programmeName: "",
      programmeMembershipType: "",
      cctDate: "2020-04-10",
      admin: "",
      lastUpdatedDate: "2020-04-10"
    },
    {
      gmcReferenceNumber: "7439961",
      doctorFirstName: "Iannish Dhana",
      doctorLastName: "Sadien",
      submissionDate: "2015-09-08",
      dateAdded: "2018-03-20",
      underNotice: "NO",
      sanction: "No",
      doctorStatus: "",
      programmeName: "",
      programmeMembershipType: "",
      cctDate: "2020-04-10",
      admin: "",
      lastUpdatedDate: "2020-04-10"
    },
    {
      gmcReferenceNumber: "7439982",
      doctorFirstName: "Callum Benjamin",
      doctorLastName: "Wright",
      submissionDate: "2015-09-08",
      dateAdded: "2018-03-20",
      underNotice: "NO",
      sanction: "No",
      doctorStatus: "",
      programmeName: "",
      programmeMembershipType: "",
      cctDate: "2020-04-10",
      admin: "",
      lastUpdatedDate: "2020-04-10"
    },
    {
      gmcReferenceNumber: "7439983",
      doctorFirstName: "Rachel Yi Ling",
      doctorLastName: "Kuo",
      submissionDate: "2015-09-08",
      dateAdded: "2018-03-20",
      underNotice: "NO",
      sanction: "No",
      doctorStatus: "",
      programmeName: "",
      programmeMembershipType: "",
      cctDate: "2020-04-10",
      admin: "",
      lastUpdatedDate: "2020-04-10"
    }
  ]
};
