name: Deploy to Amazon S3

on:
  workflow_dispatch:

jobs:
  deploy-alpha:
    name: Deploy to alpha
    runs-on: ubuntu-latest
    environment: pre-prod
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3.5.1
        with:
          node-version: 18.12.0
          cache: npm

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Install dependencies
        run: npm install

      - name: Build Angular App
        run: npm run build:misc && npm run build -- --configuration=production

      - name: Deploy app build to S3 bucket
        run: aws s3 sync ./dist/revalidation/ s3://${{ secrets.AWS_S3_BUCKET_ALPHA }} --delete

      - name: Invalidate CDN Cache
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID}} --paths /*.js /*.css /static/*
