name: PR Analysis

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4.0.3
        with:
          node-version: "18"
          cache: npm

      - name: Pull down dependencies
        run: npm install

      - name: Run linting
        run: npm run lint

      - name: Build
        run: npm run build:misc && npm run build -- --configuration=production

      - name: Run unit tests
        run: npm run test:ci
