name: PR Analysis

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2.5.0
        with:
          node-version: "12.x"
          cache: npm

      - name: Pull down dependencies
        run: npm install

      - name: Run linting
        run: npm run lint

      - name: Build
        run: npm run build:misc && npm run build -- --configuration=production

      - name: Run unit tests
        run: npm run test:ci
